FORMAT: 1A
HOST: http://teapot.192.168.11.11.xip.io

# Teapot
Teapot API is an API for [Tiego](http://github.com/luan/tiego) to manage on demand docker workstations.

# Group Workstations
Workstations are the base resource of the **Teapot API**

The workstation resource has the following attributes:

  - name **string**
    - *required*, *unique*
    - *format*:
        - alphanumeric
        - dashes allowed
        - underscores **forbbiden**
  - docker_image **string**
    - *optional*: defaults to `docker:///ubuntu#trusty`
    - *format*: `docker:///<image-name>`
        - image-name must not contain `:`s
    
## Workstations Collection [/workstations]

### List all Workstations [GET]
+ Response 200 (application/json)

        [{
          "name": "trusty", "docker_image": "docker:///ubuntu#trusty"
        }, {
          "name": "wheezy", "docker_image": "docker:///debian#wheezy"
        }]

### Create a Workstation [POST]
+ Request (application/json)

        { "name": "golang", "docker_image": "docker:///golang#1.3.3" }

+ Response 201 (application/json)

        { "name": "golang", "docker_image": "docker:///golang#1.3.3" }

## Workstation [/workstations/{name}]
A single Workstation object with all its details

+ Parameters
    + name (required, string, `golang`) ... String `name` of the Workstation to perform action with. Has example value.

### Retrieve a Workstation [GET]
+ Response 200 (application/json)

    + Body

            { "name": "golang", "docker_image": "docker:///golang#1.3.3" }

### Remove a Workstation [DELETE]
+ Response 204

